name: Build and Push Docker Images on main

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Injecte le secret dans backend/.env
      - name: Create backend .env file
        run: |
          echo "MY_SECRET=${{ secrets.MY_SECRET }}" > backend/.env

      # Injecte le même secret dans frontend/.env (si nécessaire)
      - name: Create frontend .env file
        run: |
          echo "MY_SECRET=${{ secrets.MY_SECRET }}" > frontend/.env

      - name: Build and push backend Docker image
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:backend .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:backend

      - name: Build and push frontend Docker image
        working-directory: ./frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:frontend .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:frontend
